### ISSUE TITLE
Documentation for PaperMC download API needs update

### ISSUE THREAD

**Issue by Omig12** [MinecraftServerControl/MinecraftServerControl.github.io#1]
Current docs: https://paper.readthedocs.io/en/latest/site/api.html#endpoint-documentation

The change requires a fix to keep the server build code consistent with new builds as there are downloaded.

https://papermc.io/api/v1/paper/1.16.2/latest/download => `paper-163.jar`

Where 163 equals the build version at the time of writing, the following endpoint should return the correct info of current version: https://papermc.io/api/v1/paper/1.16.2/latest

Maybe capturing version number from that query or maybe adding a routine for renaming the downloaded version to `paperclip.jar`

**Comment by Omig12** [comment]
Thank you all for such wonderful work, it saved me from a lot of headaches. ❤️

**Comment by zanix** [comment]
#4 was merged, it should work for now
However, I agree with @sandain that our update function could use some enhancements
